[package]
name = "entry_star"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv.workspace = true
excel_parser = {path = "../excel_parser"}

[[bin]]
name = "parser_star"

